Introduce logtest.New and a env variable to control verbosity during tests (#2603)
## Motivation

Closes https://github.com/spacemeshos/go-spacemesh/issues/2598

## Changes

- it is possible to control verbosity of all tests during test run with TEST_LOG_LEVEL env variable
In order to allow `go test ./...` TEST_LOG_LEVEL needs to be used instead of a flag. Otherwise module that do not import logtest will fail with unknown flag.
- if tests are executed without `-v` then only logs from failed tests will be printed

Example:

```
go test ./mesh/ -run=TestMeshDB
--- FAIL: TestMeshDB_GetStateProjection (0.00s)
    logger.go:130: 2021-07-28T08:36:26.971+0300	DEBUG	added block 91adc7dc3a to layer 5
    logger.go:130: 2021-07-28T08:36:26.971+0300	DEBUG	save contextual validity 91adc7dc3a true
    logger.go:130: 2021-07-28T08:36:26.972+0300	INFO	SaveLayerInputVectorByID: Saving input vector	{"layer_id": 5, "hash": "2594b6a92ebfb1c3312deb7d01c015fb95e9fbe9bd7bc6b527af07813ec7b910", "name": ""}
    meshdb_test.go:333: 
        	Error Trace:	meshdb_test.go:333
        	Error:      	Should not be: 2
        	Test:       	TestMeshDB_GetStateProjection
FAIL
FAIL	github.com/spacemeshos/go-spacemesh/mesh	0.102s
FAIL
```

```
go test ./mesh/ -run=TestMeshDB -log=info
--- FAIL: TestMeshDB_GetStateProjection (0.00s)
    logger.go:130: 2021-07-28T08:39:36.374+0300	INFO	SaveLayerInputVectorByID: Saving input vector	{"layer_id": 5, "hash": "2594b6a92ebfb1c3312deb7d01c015fb95e9fbe9bd7bc6b527af07813ec7b910", "name": ""}
    meshdb_test.go:333: 
        	Error Trace:	meshdb_test.go:333
        	Error:      	Should not be: 2
        	Test:       	TestMeshDB_GetStateProjection
FAIL
FAIL	github.com/spacemeshos/go-spacemesh/mesh	0.104s
FAIL
```

## Test Plan
<!-- Please specify how these changes were tested 
(e.g. unit tests, manual testing, etc.) -->

## TODO
<!-- This section should be removed when all items are complete -->
- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes
<!-- Please uncheck these items as applicable to make DevOps aware of changes that may affect releases -->
- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)