Fixing flaky poet tests on windows (#5074)
## Motivation
A few PoET test fail on windows because the test cleanup fails to remove temporary directories created during the test. For instance here: https://github.com/spacemeshos/go-spacemesh/actions/runs/6297761414/job/17095365624

```
=== RUN   TestAdminEvents
...
    testing.go:1225: TempDir RemoveAll cleanup: remove C:\Users\RUNNER~1\AppData\Local\Temp\TestAdminEvents2616476190\001\poet\db\proofs\000001.log: The process cannot access the file because it is being used by another process.
--- FAIL: TestAdminEvents (69.10s)
```

## Changes
- Ensure PoET Service is closed before the test ends.

## Test Plan
existing tests pass

## TODO
<!-- This section should be removed when all items are complete -->
- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed