Fix clock test timeout issue (#2166)
## Motivation

Fixes this issue which has been happening a lot lately in the unit tests:

```
--- FAIL: TestClock_TickPastGenesis (0.05s)
    clock_test.go:80: 
        	Error Trace:	clock_test.go:80
        	Error:      	Should be true
        	Test:       	TestClock_TickPastGenesis
        	Messages:   	tick happened too soon (49.995825ms)
```

Cherry-pick @noamnelke's fix from
88a1b879f6a9d29e538fe6995eb4c2957053a900 per https://github.com/spacemeshos/go-spacemesh/issues/1861#issuecomment-714275685

## Changes
Per Noam:

> The problem is that we're initializing the clock with the current time, do a couple of other things and then start measuring time - it should be the other way around, since we do allow some variance in the other direction (if things take a little longer).

## Test Plan
N/A, this fixes a test